name: Build_Watan_Attendance_System

on:
  push:
    branches: [ main ] # سيتم التحزيم تلقائياً عند رفع الكود لفرع main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # تثبيت المكتبات بناءً على القائمة التي أرسلتِها
        pip install PyQt5==5.15.11 pandas==3.0.1 numpy==2.4.2 zk==0.9.4 pyinstaller==6.19.0 openpyxl

    - name: Build EXE with PyInstaller
      run: |
        # التحزيم في ملف واحد مع إضافة الصور والستايل
        pyinstaller --noconfirm --onefile --windowed `
        --icon="icon.ico" `
        --add-data "logo.jpg;." `
        --add-data "styles.py;." `
        --hidden-import="pandas" `
        --hidden-import="PyQt5.sip" `
        --name "WatanAttendance_Final" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Final_Program_EXE
        path: dist/WatanAttendance_Final.exe
